### ISSUE TITLE
Make it possible to install through zpm

### ISSUE THREAD

**Issue by isc-tleavitt** [SeanConnelly/CloudStudio#1]
It would be really great if this could be installed through zpm (or if there were at least instructions on how to install, though it's fairly easy to work out)

**Comment by SeanConnelly** [comment]
Hi Timothy, in the process of figuring out how to implement ZPM / reading docs. I've commited an initial module.xml to this repo, but not pushed it anywhere else yet. I think I am on the right track, but not sure how the CLS folder gets imported. Any pointers appreciated, and then I will pick this thread of work up again. Thanks.

**Comment by isc-tleavitt** [comment]
@SeanConnelly thanks! I'll fork and see if I can figure it out.
